#!/bin/zsh

TEST_INPUT=false
while getopts 't' OPTION; do
  case "$OPTION" in
    t)
      TEST_INPUT=true
      ;;
  esac
done
shift "$(($OPTIND -1))"

DAY=$1
PADDED_DAY=${(l:2::0:)DAY}
YEAR=${2:-2021}
INPUT_URL="https://adventofcode.com/$YEAR/day/$1/input"

SCRIPT_DIR=${0:a:h}
SESSION_LOCATION="$SCRIPT_DIR/.aoc.session"
SESSION_COOKIE=`cat $SESSION_LOCATION`

if [ "$TEST_INPUT" = true ]
then
  OUTPUT_FILE="$SCRIPT_DIR/../years/$YEAR/inputs/input$PADDED_DAY-test.txt"
  touch "$OUTPUT_FILE"
else
  OUTPUT_FILE="$SCRIPT_DIR/../years/$YEAR/inputs/input$PADDED_DAY.txt"
  curl "$INPUT_URL" -H "cookie: $SESSION_COOKIE" --output "$OUTPUT_FILE"
fi
